apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
#  - port: 18555
#    targetPort: 18555
  - port: {{ .Values.service.http.externalPort }}
    targetPort: {{ .Values.service.http.internalPort }}
    protocol: TCP
    name: http
#  - port: 18556
#    targetPort: 18556
  - port: {{ .Values.service.rpc.externalPort }}
    targetPort: {{ .Values.service.rpc.internalPort }}
    protocol: TCP
    name: rpc
  selector:
    app: {{ template "fullname" . }}
