kind: PersistentVolume
apiVersion: v1
metadata:
  name: lightning-kube-pvX_NETWORK_SUFFIX_X
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: X_STORAGE_X
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/vda1/lk/btcd"
    type: DirectoryOrCreate
