# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.101.117.209:5000/kevinstl/lightning-kube-btcd
  tag: 0.0.7
  pullPolicy: IfNotPresent
service:
  name: lightning-kube-btcd
  type: LoadBalancer
  externalPort: 18556
  internalPort: 18556
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 1000m
    memory: 3072Mi
  requests:
    cpu: 25m
    memory: 96Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
