kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lightning-kube-pvc
  namespace: lightning-kube
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
