kind: PersistentVolume
apiVersion: v1
metadata:
  name: lightning-kube-pvX_NETWORK_SUFFIX_X
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
#    path: "/host-home/minikube"
    path: "/tmp"
