kind: PersistentVolume
apiVersion: v1
metadata:
  name: X_NAME_X
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt"
