---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: lightning-kube-pvX_NETWORK_SUFFIX_X
  annotations:
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  finalizers:
  - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 50Gi
  hostPath:
    path: "/host-home/minikube"
    type: ''
  accessModes:
  - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: lightning-kube-testnet
    name: lightning-kube-pvc-testnet
    apiVersion: v1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
