kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lightning-pvc
  namespace: lightning-kube
spec:
  storageClassName: lightning-shared
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi